version: 2

models:
  - name: transform
    description: "Dataset des trajets en taxi jaune de New York au cours de Janvier 2023"
    columns:
      - name: VendorID
        description: "A code indicating the TPEP provider that provided the record."
      - name: tpep_pickup_datetime
        description: "The date and time when the meter was engaged."
      - name: tpep_dropoff_datetime
        description: "The date and time when the meter was disengaged."
      - name: Passenger_count
        description: "The number of passengers in the vehicle."
      - name: Trip_distance
        description: "The elapsed trip distance in miles reported by the taximeter."
      - name: PULocationID
        description: "The taxi zone where the trip started."
      - name: DOLocationID
        description: "The taxi zone where the trip ended."
      - name: RateCodeID
        description: "The final rate code in effect at the end of the trip."
      - name: Payment_type
        description: "A numeric code signifying how the passenger paid for the trip."
      - name: Fare_amount
        description: "The time-and-distance fare calculated by the meter."
      - name: Extra
        description: "Miscellaneous extras and surcharges."
      - name: MTA_tax
        description: "0.50 MTA tax that is automatically triggered based on the metered rate in use."
      - name: Tip_amount
        description: "Tip amount – This field is automatically populated for credit card tips."
      - name: Tolls_amount
        description: "Total amount of all tolls paid in trip."
      - name: improvement_surcharge
        description: "0.30 improvement surcharge assessed on hailed trips at the flag drop."
      - name: Total_amount
        description: "The total amount charged to passengers."
      - name: congestion_surcharge
        description: "The surcharge amount for trips that pass through a Congestion Pricing Zone."
      - name: store_and_fwd_flag
        description: "This flag indicates whether the trip record was held in vehicle memory before sending to the vendor."
      - name: Airport_fee
        description: "$1.25 for pick up only at LaGuardia and John F. Kennedy Airports"