version: 2

sources:
  - name: tlc
    meta:
      external_location: 'https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-01.parquet'
      formatter: oldstyle
    tables:
      - name: transform_file